// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLPhongTro.API.Data;

#nullable disable

namespace QLPhongTro.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLPhongTro.API.Models.BieuMau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiBieuMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBieuMau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BieuMaus");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ChiSoCongTo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChiSoCu")
                        .HasColumnType("int");

                    b.Property<int>("ChiSoMoi")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiCongTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<int>("SoTieuThu")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThangNam")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhongTroId");

                    b.ToTable("ChiSoCongTos");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ChiSoCongToGuiTuThue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhCongTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChiSo")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachThueId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiCongTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThangNam")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KhachThueId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("ChiSoCongToGuiTuThues");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.DayTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoPhongMoiTang")
                        .HasColumnType("int");

                    b.Property<int>("SoTang")
                        .HasColumnType("int");

                    b.Property<string>("TenDayTro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DayTros");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DayTroId")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaMacDinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DayTroId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhMinhChung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CongNoThangTruoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DaGuiEmail")
                        .HasColumnType("bit");

                    b.Property<string>("FileHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThangNam")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienInternet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienVeSinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.HasIndex("PhongTroId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KhachThueId")
                        .HasColumnType("int");

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KhachThueId");

                    b.HasIndex("MaHopDong")
                        .IsUnique();

                    b.HasIndex("PhongTroId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.KhachThue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhCCCDMatSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnhCCCDMatTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("KhachChinhId")
                        .HasColumnType("int");

                    b.Property<bool>("LaKhachChinh")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayBatDauThue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucThue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThaiCoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachChinhId");

                    b.HasIndex("PhongTroId");

                    b.HasIndex("UserId");

                    b.ToTable("KhachThues");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.LichSuChuyenPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachThueId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayChuyen")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongTroCuId")
                        .HasColumnType("int");

                    b.Property<int>("PhongTroMoiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachThueId");

                    b.ToTable("LichSuChuyenPhongs");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Code", "Purpose");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.PhongTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayTroId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GioiHanSoNguoi")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DayTroId");

                    b.HasIndex("SoPhong")
                        .IsUnique();

                    b.ToTable("PhongTros");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DayTroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DayTroId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ThongBaoDaDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayDoc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThongBaoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ThongBaoId", "UserId")
                        .IsUnique();

                    b.ToTable("ThongBaoDaDocs");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.YeuCauChinhSua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhMinhHoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachThueId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiYeuCau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongTroId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KhachThueId");

                    b.HasIndex("PhongTroId");

                    b.ToTable("YeuCauChinhSuas");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.BieuMau", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ChiSoCongTo", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany("ChiSoCongTos")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ChiSoCongToGuiTuThue", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.KhachThue", "KhachThue")
                        .WithMany("ChiSoCongToGuiTuThues")
                        .HasForeignKey("KhachThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.DayTro", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.DichVu", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.DayTro", "DayTro")
                        .WithMany()
                        .HasForeignKey("DayTroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DayTro");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.HoaDon", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany("HoaDons")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.HopDong", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.KhachThue", "KhachThue")
                        .WithMany("HopDongs")
                        .HasForeignKey("KhachThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.KhachThue", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.KhachThue", "KhachChinh")
                        .WithMany("NguoiOKem")
                        .HasForeignKey("KhachChinhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany("KhachThues")
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhongTro.API.Models.User", "User")
                        .WithMany("LichSuThue")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhachChinh");

                    b.Navigation("PhongTro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.LichSuChuyenPhong", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.KhachThue", "KhachThue")
                        .WithMany("LichSuChuyenPhongs")
                        .HasForeignKey("KhachThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachThue");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.PhongTro", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.DayTro", "DayTro")
                        .WithMany("PhongTros")
                        .HasForeignKey("DayTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DayTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ThongBao", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.DayTro", "DayTro")
                        .WithMany()
                        .HasForeignKey("DayTroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLPhongTro.API.Models.User", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DayTro");

                    b.Navigation("NguoiTao");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ThongBaoDaDoc", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.ThongBao", "ThongBao")
                        .WithMany("ThongBaoDaDocs")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhongTro.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThongBao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.YeuCauChinhSua", b =>
                {
                    b.HasOne("QLPhongTro.API.Models.KhachThue", "KhachThue")
                        .WithMany("YeuCauChinhSuas")
                        .HasForeignKey("KhachThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLPhongTro.API.Models.PhongTro", "PhongTro")
                        .WithMany()
                        .HasForeignKey("PhongTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachThue");

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.DayTro", b =>
                {
                    b.Navigation("PhongTros");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.KhachThue", b =>
                {
                    b.Navigation("ChiSoCongToGuiTuThues");

                    b.Navigation("HopDongs");

                    b.Navigation("LichSuChuyenPhongs");

                    b.Navigation("NguoiOKem");

                    b.Navigation("YeuCauChinhSuas");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.PhongTro", b =>
                {
                    b.Navigation("ChiSoCongTos");

                    b.Navigation("HoaDons");

                    b.Navigation("HopDongs");

                    b.Navigation("KhachThues");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.ThongBao", b =>
                {
                    b.Navigation("ThongBaoDaDocs");
                });

            modelBuilder.Entity("QLPhongTro.API.Models.User", b =>
                {
                    b.Navigation("LichSuThue");
                });
#pragma warning restore 612, 618
        }
    }
}
